apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: skycards
resources:
  - namespace.yaml
  - sealedsecret.yaml
  - webhooks-config.yaml
  - cronjob-airports.yaml
  - cronjob-models.yaml
  - cronjob-airlines.yaml
